import { createRequire } from 'node:module'
import { mkdir, writeFile } from 'node:fs/promises'
const require = createRequire(import.meta.url)
const { chromium } = require('playwright')
const base = process.env.TEST_URL || 'http://127.0.0.1:4173'
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH })
const checks = [], failures = [], media = []
const expect = (condition, message) => (condition ? checks : failures).push(message)
await mkdir('artifacts', { recursive: true })
try {
  for (const width of [1440, 768, 390]) {
    const context = await browser.newContext({ viewport: { width, height: width === 390 ? 844 : 900 } })
    const page = await context.newPage()
    page.on('pageerror', error => failures.push(error.message))
    await page.goto(base, { waitUntil: 'domcontentloaded' })
    await page.waitForSelector('.cinematic-hero')
    await page.waitForFunction(() => document.querySelector('video').readyState >= 2, null, { timeout: 45000 }).catch(() => {})
    await Promise.race([page.evaluate(() => document.fonts.ready.then(() => true)), page.waitForTimeout(6000)])
    await page.waitForTimeout(1500)
    const state = await page.locator('video').evaluate(v => ({ readyState: v.readyState, width: v.videoWidth, height: v.videoHeight, paused: v.paused, muted: v.muted, loop: v.loop, inline: v.playsInline, time: v.currentTime, error: v.error?.message }))
    media.push({ viewportWidth: width, ...state })
    expect(state.readyState >= 2 && !state.paused, `${width}: background video plays`)
    expect(state.muted && state.loop && state.inline, `${width}: silent inline looping video`)
    expect(await page.locator('h1').count() === 1, `${width}: one heading`)
    expect(await page.locator('#work .project-card').count() === 4, `${width}: all four projects retained`)
    expect(await page.locator('#about').count() === 1 && await page.locator('#contact').count() === 1, `${width}: experience and contact retained`)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${width}: no horizontal overflow`)
    const before = state.time
    await page.waitForFunction(time => document.querySelector('video').currentTime !== time, before, { timeout: 15000 }).catch(() => {})
    expect(await page.locator('video').evaluate(v => v.currentTime) !== before, `${width}: video advances`)
    await page.getByRole('button', { name: '暂停动效', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('video').paused)
    expect(await page.locator('video').evaluate(v => v.paused), `${width}: video can pause`)
    await page.screenshot({ path: `artifacts/cinematic-hero-${width}.png` })
    await page.reload({ waitUntil: 'domcontentloaded' })
    await page.waitForFunction(() => document.documentElement.dataset.motion === 'paused')
    expect(await page.locator('video').evaluate(v => v.paused), `${width}: pause preference persists`)
    await page.getByRole('button', { name: '启用动效', exact: true }).click()
    await page.waitForFunction(() => !document.querySelector('video').paused)
    await page.locator('#work').scrollIntoViewIfNeeded()
    await page.waitForFunction(() => document.querySelector('video').paused)
    expect(await page.locator('video').evaluate(v => v.paused), `${width}: offscreen video pauses`)
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
    await page.waitForFunction(() => !document.querySelector('video').paused)
    expect(await page.locator('video').evaluate(v => !v.paused), `${width}: visible video resumes`)
    if (width === 390) {
      await page.getByRole('button', { name: '打开导航' }).click()
      expect(await page.getByRole('navigation', { name: '手机导航' }).isVisible(), 'Mobile menu opens')
      await page.screenshot({ path: 'artifacts/cinematic-menu-390.png' })
      await page.keyboard.press('Escape')
      expect(await page.getByRole('navigation', { name: '手机导航' }).count() === 0, 'Escape closes mobile menu')
      await page.getByRole('button', { name: '打开导航' }).click()
      await page.getByRole('navigation', { name: '手机导航' }).getByRole('link', { name: '关于' }).click()
      expect(await page.getByRole('navigation', { name: '手机导航' }).count() === 0, 'Mobile anchor closes menu')
    }
    await context.close()
  }
  const reduced = await browser.newContext({ reducedMotion: 'reduce' })
  const page = await reduced.newPage()
  await page.goto(base, { waitUntil: 'domcontentloaded' })
  await page.waitForFunction(() => document.documentElement.dataset.motion === 'paused')
  expect(await page.locator('video').evaluate(v => v.paused), 'Reduced motion pauses video')
  expect(await page.locator('h1').evaluate(e => getComputedStyle(e).animationName) === 'none', 'Reduced motion removes title animation')
  await reduced.close()
  const fallback = await browser.newContext({ viewport: { width: 390, height: 844 } })
  await fallback.route('https://d8j0ntlcm91z4.cloudfront.net/**', route => route.abort())
  const fallbackPage = await fallback.newPage()
  await fallbackPage.goto(base, { waitUntil: 'domcontentloaded' })
  expect(await fallbackPage.getByRole('heading', { name: /把智能体/ }).isVisible(), 'Video unavailable: heading remains readable')
  expect(await fallbackPage.getByRole('link', { name: '探索我的作品' }).isVisible(), 'Video unavailable: project CTA remains accessible')
  await fallbackPage.screenshot({ path: 'artifacts/cinematic-fallback.png' })
  await fallback.close()
  const result = { base, checks: checks.length, failures, media }
  await writeFile('artifacts/cinematic-check.json', JSON.stringify(result, null, 2))
  console.log(JSON.stringify(result, null, 2))
} finally { await browser.close() }
if (failures.length) process.exit(1)
